#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i="0"

while [ "$i" -le 10 ]
do
if [ "$i" = 4 ]
   then
        echo "bad luck"
	elif ["$i" = 8 ]
	echo "good luck"
	((i++))
	fi
	echo "Best School"
	((i++))
	done