#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i="0"

while [ "$i" -le 9 ]
do
if [ "$i" = 3 ]
   then
       echo "bad luck"
       ((i++))
	elif ["$i" = 7 ]
	     then
	     echo "good luck"
		else
	echo "Best School"
	((i++))
	fi
	done
