#!/usr/bin/env bash
# This script is displaying


i="0"
m="0"

while [ "$i" -le 59 ]
do
    if [ "$i" = 0 ]
    then
	echo "Hour: $m"
	((i++))
	((m++))
    elif [ "$i" = 59 ]
    then
return 0
    else ((i++))
    fi
done
